name: Test PR

on:
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm ci

      - name: test
        run: |
          npm run test:e2e
          npm run test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
